### PR TITLE
Feature/cplp 1342/download document

### PR DESCRIPTION
**Pull request by nidhigarg-bmw**

### CODE REVIEW

**Review by lavanya-bmw — APPROVED** [review]
lgtm

**Review by lavanya-bmw — CHANGES_REQUESTED** [review]
Sorry didn't check the conflicts. Please fix conflicts.

**Comment by nidhigarg-bmw** [comment]
> Sorry didn't check the conflicts. Please fix conflicts.

Fixed now

**Review by lavanya-bmw — APPROVED** [review]
okay now

**Pull request merged**
