### PR TITLE
Feature/cplp 509 Enabling Breadcrumb

### PR DESCRIPTION
**Pull request by PI-FerasAhmad**
Breadcrumb component improved to read the full path from router and create breadcrumb items.

### CODE REVIEW

**Comment by PI-FerasAhmad** [comment]
@oyo the base is automatically changed to main, should I changed it again to dev?

**Comment by oyo** [comment]
> @oyo the base is automatically changed to main, should I changed it again to dev?

@PI-FerasAhmad yes - please change to `dev`. Thanks :)

**Comment by PI-FerasAhmad** [comment]
@oyo I think dev is deleted after merge into main? there is no dev

**Comment by oyo** [comment]
@PI-FerasAhmad ah sorry - my fault. I branched dev again from main now

**Comment by jjeroch** [comment]
@nidhigarg-bmw  & @lavanya-bmw  can you please do a review of the pr tomorrow? Thanks!

**Review by nidhigarg-bmw — APPROVED** [review]
Okay for me

**Review by lavanya-bmw — APPROVED** [review]
Looks good

**Pull request merged**
