### PR TITLE
Error Image SVG

### PR DESCRIPTION
**Pull request by jjeroch**

### CODE REVIEW

**Review by oyo — APPROVED** [review]
why haven't you put that into the other PR? - contentwise okay

**Comment by oyo** [comment]
Created a base component `SVGImage` that can handle different ways to specify a svg image:
- svg string
- base64 encoded data url
- path to file

This is now the base to Logo, ErrorImage and any other images we will add in the future.

**Comment by jjeroch** [comment]
> why haven't you put that into the other PR? - contentwise okay

I am planning to just close / kill the other pr. Fresh clean pr created without any sonar issues

**Review by oyo — APPROVED** [review]
lgtm

**Pull request merged**
