### PR TITLE
[CPLP-1243] desing added for organization page

### PR DESCRIPTION
**Pull request by thackerronak**

### CODE REVIEW

**Review by lavanya-bmw — CHANGES_REQUESTED** [review]
Please fix the code smells

**Comment by thackerronak** [comment]
> * Please fix the code smells
> * add header template to the newly created files
> * Please add your changes to the RELEASENOTES.md file with every PR so that we can have an overview by the end of the sprint.

done

**Review by lavanya-bmw — DISMISSED** [review]
looks good to me

**Comment by jjeroch** [comment]
@thackerronak conflicts are still existing, please fix those

**Comment by thackerronak** [comment]
> @thackerronak conflicts are still existing, please fix those

done

**Review by lavanya-bmw — APPROVED** [review]

**Pull request merged**
