### PR TITLE
Feature/AAS download-link in Semantic Hub

### PR DESCRIPTION
**Pull request by JaneMcBrain**
Add the AAS-Download link for a semantic model, as defined in: https://jira.catena-x.net/browse/A1SLDT-391
Fixes Deletion Bug: https://jira.catena-x.net/browse/A1SLDT-692

### CODE REVIEW

**Comment by jjeroch** [comment]
@nidhigarg-bmw  @lavanya-bmw  please also join the review :)

**Comment by JaneMcBrain** [comment]
> @nidhigarg-bmw @lavanya-bmw please also join the review :)

I got some feedback regarding this task, and have to update some functionalities... please wait for review

**Comment by JaneMcBrain** [comment]
@nidhigarg-bmw and @lavanya-bmw feel free to check my recent changes (Martin already reviewed, but had to optimize the download)

**Review by nidhigarg-bmw — APPROVED** [review]
Looks good to me :)

**Pull request merged**
