### PR TITLE
[CPLP-1135] - Business Logic & API Connection & Style Update-Delete BPN

### PR DESCRIPTION
**Pull request by smartdeepp**

### CODE REVIEW

**Review by nidhigarg-bmw — COMMENTED** [review]
Please update Release notes. Rest looks good

**Comment by smartdeepp** [comment]
hello @nidhigarg-bmw , i have updated the release note.

**Review by nidhigarg-bmw — APPROVED** [review]

**Review by jjeroch — CHANGES_REQUESTED** [review]
@smartdeepp please do a quick recheck. I could see that "UserOwn" got also updated / changed. Is this the page with my own user details? I shouldn't be able to change or delete a bpn for myself. Can you please do a quick recheck before we move ahead with the merge

**Comment by smartdeepp** [comment]
> @smartdeepp please do a quick recheck. I could see that "UserOwn" got also updated / changed. Is this the page with my own user details? I shouldn't be able to change or delete a bpn for myself. Can you please do a quick recheck before we move ahead with the merge

So if i am not thinking wrong,  you mean to say is, If i myself am logging in, then i cannot delete the BPNs which are assigned to me

**Comment by smartdeepp** [comment]
Hello @jjeroch , i have made the changes, can you please check and let me know if anything else is required.

**Review by jjeroch — APPROVED** [review]

**Pull request merged**
