### PR TITLE
[CPLP-800] design added for app overview page

### PR DESCRIPTION
**Pull request by thackerronak**

### CODE REVIEW

**Review by lavanya-bmw — CHANGES_REQUESTED** [review]
Please fix the code smell and add the releasenotes in 0.5.5 version(available when you pull latest code) instead of 0.5.4 version.

**Comment by thackerronak** [comment]
> 

release notes updated, about code smell it is related to TODO if you check, I have mentioned `need to replace Recently changed api once it is available.`

**Review by lavanya-bmw — DISMISSED** [review]
looks good to me

**Review by jjeroch — APPROVED** [review]
Dev Approval already done, approving after merge conflicts are fixed

**Pull request merged**
