### PR TITLE
Feature/cplp 1296 datepicker

### PR DESCRIPTION
**Pull request by PI-FerasAhmad**
Date picker component created

### CODE REVIEW

**Review by oyo — CHANGES_REQUESTED** [review]
Please don't attempt to localize date and time and use global Standard ISO 8601 instead of various local formats.
image
`08/02/2022` can be interpreted as Aug 2 or Feb 8 in some regions of the world - use `2022-08-02`. The only way out of the confusion hell is if developers stop supporting crazy local formats and only support one global standard. Also this one will be sorted correctly as string while the others won't.
https://www.iso.org/iso-8601-date-and-time-format.html

**Comment by PI-FerasAhmad** [comment]
@oyo @jjeroch 
I change the input date to Standard ISO 8601, but we still have local parameter to change the month and week days between english and germany 
2022-08-03 10_40_48-Greenshot

**Review by oyo — APPROVED** [review]
I think that's a very good solution - approved now :)

**Review by oyo — APPROVED** [review]
need an approve again?

**Comment by PI-FerasAhmad** [comment]
@oyo no needed, I just removed merge conflicts  :-)

**Pull request merged**
