### PR TITLE
add app detail header element

### PR DESCRIPTION
**Pull request by nidhigarg-bmw**

### CODE REVIEW

**Review by jjeroch — CHANGES_REQUESTED** [review]
@nidhigarg-bmw Can you please check the **role validation** under 'cx-portal/src/services/accessservices' the role for the app detail page must be 'view_apps'

Inside the file 'cx-portal/src/components/pages/AppDetails' the **AppItem values** are hardcoded. I guess thats the case because the API connect is missing so far. Thats fine, but please add a comment inside the code that this section needs to get replaced with the API as soon as the API is available. We did the same for other pages in the past. It helps to keep a better transparency.

For the **locales** you can find the german translation inside the jira ticket https://jira.catena-x.net/browse/CPLP-721

**Comment by nidhigarg-bmw** [comment]
> @nidhigarg-bmw Can you please check the **role validation** under 'cx-portal/src/services/accessservices' the role for the app detail page must be 'view_apps'
> 
> Inside the file 'cx-portal/src/components/pages/AppDetails' the **AppItem values** are hardcoded. I guess thats the case because the API connect is missing so far. Thats fine, but please add a comment inside the code that this section needs to get replaced with the API as soon as the API is available. We did the same for other pages in the past. It helps to keep a better transparency.
> 
> For the **locales** you can find the german translation inside the jira ticket https://jira.catena-x.net/browse/CPLP-721

@jjeroch I checked the role and its already "view_apps". Also I added the translations.

**Review by jjeroch — APPROVED** [review]
From my side reviewed. 
Technical & methodic review is taking place by @oyo  and @fatihayyildiz

**Review by oyo — CHANGES_REQUESTED** [review]
@nidhigarg-bmw I updated your PR with a few changes:
- the page now supports a parameter `appId`
- that parameter will be used to loaded through an API call (which is still a static object)
- after the data has been loaded it is handed over to the header component as a prop

Test: http://localhost:3000/appdetail/234

There are still a few things looking different to the figma designs
- lead picture has no rounded corners
- the rating doesn't support 'half' stars and doesn't show the value (see https://mui.com/material-ui/react-rating/ for an example how this can be implemented)

**Pull request merged**
