### PR TITLE
[CPLP-1006] footer visible while data is being load -  done

### PR DESCRIPTION
**Pull request by smartdeepp**

### CODE REVIEW

**Review by lavanya-bmw — APPROVED** [review]
looks good to me

**Review by oyo — APPROVED** [review]
setting the min-height will solve the issue - but then the footer will always be out of the screen even if there is no data loaded or only one or two rows.

in my other open PR I solved the issue for the technical users in a different way where a white element is displayed only during loading time. [cx-portal/src/components/shared/basic/Empty/index.tsx](https://github.com/catenax-ng/product-portal-frontend/pull/235/files#diff-2a1f174b7601e53ca7b08104eb4deb3d82263fc06a7f34e2982fba3e32488d45)

@jjeroch I guess we can approve and check which solution we like better and then use that one for all pages.

**Comment by jjeroch** [comment]
> setting the min-height will solve the issue - but then the footer will always be out of the screen even if there is no data loaded or only one or two rows.
> 
> in my other open PR I solved the issue for the technical users in a different way where a white element is displayed only during loading time. [cx-portal/src/components/shared/basic/Empty/index.tsx](https://github.com/catenax-ng/product-portal-frontend/pull/235/files#diff-2a1f174b7601e53ca7b08104eb4deb3d82263fc06a7f34e2982fba3e32488d45)
> 
> @jjeroch I guess we can approve and check which solution we like better and then use that one for all pages.

@oyo that was the plan, the footer should be not showing up while content is loaded. But as soon as content is loaded the footer should move up (if content is smaller then the actual screen height)
If its not working like this, I suggest we actually keep the pr unapproved

**Review by oyo — CHANGES_REQUESTED** [review]
we now have a different solution for the problem - and we will eventually close this PR

**Comment by smartdeepp** [comment]
> we now have a different solution for the problem - and we will eventually close this PR

Hello @oyo , so am i suppose to do the changes in this ongoing thread?

**Pull request closed without merging**
