### PR TITLE
HF Registration Request

### PR DESCRIPTION
**Pull request by jjeroch**
Headline deleted and new introduction text added

### CODE REVIEW

**Comment by jjeroch** [comment]
@oyo  do you want to be my reviewer? ;) quick question - if I dont want to have a central aligned text, I only kick out the "align" section....is this correct?

**Review by oyo — CHANGES_REQUESTED** [review]
The unit tests for RegistrationRequests are failing with your changes :O

`      19 |   // Check page title to be sure page rendered correctly
      20 |   expect(
    > 21 |     screen.getByText(
         |            ^
      22 |       EnglishScripts.content.admin['registration-requests'].headertitle
      23 |     )
      24 |   ).toBeInTheDocument()
`

**Comment by jjeroch** [comment]
> The unit tests for RegistrationRequests are failing with your changes :O
> 
> ` 19 | // Check page title to be sure page rendered correctly 20 | expect( > 21 | screen.getByText( | ^ 22 | EnglishScripts.content.admin['registration-requests'].headertitle 23 | ) 24 | ).toBeInTheDocument()`

@oyo  thanks for the remark. As discussed I kicked this out since I dont see this as necessary unit test and the header got deleted. Now we have some generic text value, but I would not run any unit tests on this section

**Comment by oyo** [comment]
> @oyo do you want to be my reviewer? ;) quick question - if I dont want to have a central aligned text, I only kick out the "align" section....is this correct?

@jjeroch if there is some text-align: center - then simply remove that. But better open the section in the browser dev tools and uncheck that css setting to be sure it doesn't affect other parts.

**Review by oyo — APPROVED** [review]
approved now :)

**Pull request merged**
