### PR TITLE
Delete my user api integration

### PR DESCRIPTION
**Pull request by manojava-gk**

### CODE REVIEW

**Comment by manojava-gk** [comment]
Notes already has this update.

**Comment by jjeroch** [comment]
@manojava-gk FYI - pr is in DRAFT state - not sure if this is intended

**Comment by manojava-gk** [comment]
> @manojava-gk FYI - pr is in DRAFT state - not sure if this is intended

Usually will make Ready for review after/before adding reviewers. This time, I forgot to move it. Thanks for the notice :)

**Review by lavanya-bmw — APPROVED** [review]
lgtm

**Pull request merged**
