### PR TITLE
feature CPLP-1139 notification prototype

### PR DESCRIPTION
**Pull request by oyo**
- notifications currently coming from static test data: https://portal.dev.demo.catena-x.net/assets/api/notification/all.json

### CODE REVIEW

**Comment by jjeroch** [comment]
@PI-FerasAhmad  can you please have a special look at the components
@nidhigarg-bmw  & @lavanya-bmw  please review with focus on the "feature" files
I had a look at the locals, thats all fine
@oyo  great that the locales have been divided. Thats good (y)

**Review by PI-FerasAhmad — DISMISSED** [review]
looks good to me, just one code Smell :-)

**Comment by oyo** [comment]
@PI-FerasAhmad fixed that code smell and resolved some merge conflicts that arose in the meantime. Can you please confirm again? thanks :)

**Review by PI-FerasAhmad — DISMISSED** [review]

**Comment by oyo** [comment]
@PI-FerasAhmad sorry, fixing sonar I introduced a bug that I had to fix again :/ could you help me again? thanks

**Review by PI-FerasAhmad — APPROVED** [review]

**Review by nidhigarg-bmw — APPROVED** [review]
Looks good

**Review by lavanya-bmw — APPROVED** [review]
Looks good to me

**Pull request merged**
