### PR TITLE
Select list component: disable clear feature added

### PR DESCRIPTION
**Pull request by ajithsimons**
Select list component: disable clear feature added as an optional parameter.

### CODE REVIEW

**Comment by jjeroch** [comment]
@lavanya-bmw & @oyo proposal from Ajith regarding enhancing the component for select-list defaults.
Important: we need to make sure that the change from Ajith also considers the update / publishing in storybook and that this enhancement doesn't break our current implementations such as app-release-process

**Review by lavanya-bmw — DISMISSED** [review]
lgtm

**Comment by jjeroch** [comment]
@lavanya-bmw  I fixed the changelog. Can you please "approve" once more?

**Review by lavanya-bmw — APPROVED** [review]
lgtm

**Pull request merged**
